training_args:
  num_train_epochs: 80
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  report_to: wandb
  remove_unused_columns: False
  ddp_find_unused_parameters: False
  save_strategy: steps
  save_steps: 4000
  save_total_limit: 1
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 4000
  learning_rate: 1e-4
  dataloader_num_workers: 4
  auto_output_dir: True
  auto_output_root: outputs/demos
  lr_scheduler_type: cosine
  alpha_teacher: 0.90
  alpha_center: 0.90
  # dataloader_persistent_workers: True
  # generation_config: null
