training_args:
  num_train_epochs: 500
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  report_to: wandb
  remove_unused_columns: False
  # ddp_find_unused_parameters: True
  save_strategy: steps
  save_steps: 100
  save_total_limit: 1
  logging_steps: 1
  eval_strategy: "no"
  # eval_steps: 2000
  learning_rate: 1e-4
  dataloader_num_workers: 6
  auto_output_dir: True
  auto_output_root: outputs/demos
  lr_scheduler_type: linear
  alpha_teacher: 0.7
  # alpha_center: 0.7
  # temperature_student: 0.1
  temperature_teacher: 0.07
  # do_eval: False

  # dataloader_persistent_workers: True
  # generation_config: null
