config:
  hidden_size: 768
  backbone_type: dinov2-with-token-sampler
  backbone_kwargs:
    id: facebook/dinov2-with-registers-base
    output_layer: -2
    num_heads: 12
    num_adapter_layers: 2
    num_extra_queries: 4
